FROM python:3.11

COPY expect_response.exp .

RUN apt-get update
RUN apt-get install expect -y
RUN chmod +x expect_response.exp
RUN expect expect_response.exp
RUN pip install pynput
RUN apt-get install ffmpeg libsm6 libxext6 -y
RUN pip install opencv-python
RUN pip install mediapipe
RUN pip install tensorflow[and-cuda]==2.12.0


COPY hand-signs.py /hand-tracking/cam-script.py
COPY gesture.names.txt /hand-tracking/gesture.names.txt
COPY gestures /hand-tracking/gestures

WORKDIR /hand-tracking

CMD ["python", "cam-script.py"]
